In [2]:
import tensorflow as ts
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sn
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
from PIL import Image
import warnings
warnings.filterwarnings('ignore')
import random
random.seed(10)
from os import listdir
from keras.utils import to_categorical
from skimage.io import imread
from os import listdir
from matplotlib.pyplot import imread
from skimage.transform import resize
from sklearn.model_selection import train_test_split

In [3]:
# Settings:
img_size = 64
grayscale_images = True
num_class = 10
test_size = 0.2

In [4]:
def get_img_RGB(data_path):
    # Getting image array from path:
    img = imread(data_path)
    img = resize(img, (img_size, img_size, 3))
    return img

In [17]:
def get_dataset(dataset_path='Dataset'):
    
    # Getting all data from data path
    labels = listdir(dataset_path)  # Geting labels
    X = []
    Y = []
    Z = []
    for i, label in enumerate(labels):
        datas_path = dataset_path + '/' + label
        for data in listdir(datas_path):
            img = get_img_RGB(datas_path + '/' + data)
            #plt.matshow(img)
            X.append(img)
            Z.append(img)
            Y.append(i)
        # Create dateset:
    #X = 1 - np.array(X).astype('float32') / 255.
    X = np.array(X).astype('float32')
    Y = np.array(Y).astype('float32')
    m=X.mean()
    #Y = to_categorical(Y, num_class)
    X, X_test, Y, Y_test = train_test_split(X, Y, test_size=test_size, random_state=None)
    return X, X_test, Y, Y_test,Z , m

In [18]:
x_train, x_test, y_train, y_test , img , m = get_dataset('D:\Sign-Language-Digits-Dataset-master\Dataset')

In [34]:
print(x_train.shape)
x_train = x_train.reshape(len(x_train),64*64 , 3)
x_test = x_test.reshape(len(x_test),64*64 , 3)
print(m)
print(x_train[0])
print("==================================")
for i  in range(x_train.shape[0]):
    for j in range(x_train.shape[1]): 
        x_train[i][j] = (x_train[i][j] - m) 
print(x_train[0])


(1649, 4096, 3)
0.6419269
[[-0.15736806 -0.1463961  -0.11141217]
 [-0.15124062 -0.13947588 -0.10435414]
 [-0.1411916  -0.1294269  -0.09413278]
 ...
 [-0.28056812 -0.2846965  -0.2997279 ]
 [-0.2884955  -0.29241708 -0.30810335]
 [-0.29383022 -0.29775178 -0.31343806]]
[[-0.79929495 -0.788323   -0.75333905]
 [-0.7931675  -0.78140277 -0.746281  ]
 [-0.7831185  -0.7713538  -0.73605967]
 ...
 [-0.922495   -0.92662334 -0.9416548 ]
 [-0.9304224  -0.93434393 -0.9500302 ]
 [-0.9357571  -0.93967867 -0.95536494]]
